import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { LegalChrome, h2Style, pStyle } from "@/components/LegalChrome";
import { breadcrumbJsonLd } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms for using Lumin: what the waitlist is, what our recommendations are and aren't, affiliate disclosure, and acceptable use.",
  alternates: { canonical: "/terms" },
  openGraph: {
    title: "Terms of Service · Lumin",
    description: "The terms that govern using Lumin's AI skin analysis service.",
    url: "/terms",
  },
};

const crumbs = [
  { name: "Home", path: "/" },
  { name: "Terms of Service", path: "/terms" },
];

export default function TermsPage() {
  return (
    <LegalChrome>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd(crumbs)) }}
      />
      <Breadcrumbs items={crumbs} />

      <h1 style={{ fontFamily: "'Hanken Grotesk', sans-serif", fontWeight: 900, fontSize: "clamp(34px, 5vw, 52px)", color: "#1a1c1b", letterSpacing: "-1.5px", lineHeight: 1.1, margin: "0 0 8px" }}>
        Terms of Service
      </h1>
      <p style={{ ...pStyle, fontSize: 14 }}>Last updated: December 31, 2026</p>

      <div className="neo-border p-5 my-8" style={{ background: "#e8e883" }}>
        <p style={{ ...pStyle, margin: 0, color: "#1a1c1b" }}>
          <strong>The short version:</strong> the waitlist is free. Lumin gives
          cosmetic suggestions, not medical advice. Some product links earn us
          a commission at no cost to you, and we label them. Be 18+, don&apos;t
          abuse the service.
        </p>
      </div>

      <h2 style={h2Style}>The waitlist</h2>
      <p style={pStyle}>
        Joining the Lumin waitlist is free. You give us your email, confirm it,
        and answer a short skin quiz. Joining doesn&apos;t guarantee a launch
        date, a specific place in line, or that the product will include any
        particular feature. We may change or cancel the beta.
      </p>

      <h2 style={h2Style}>Not medical advice</h2>
      <p style={pStyle}>
        Lumin provides cosmetic and general wellness information to help you
        choose skincare products. It is not a medical device, it does not
        diagnose, treat, cure, or prevent any condition, and it is not a
        substitute for a dermatologist or doctor. If you have a persistent,
        painful, spreading, or changing skin problem, please see a qualified
        healthcare professional. Never delay seeking medical advice because of
        something Lumin suggested.
      </p>
      <p style={pStyle}>
        We ask about pregnancy, prescription treatments, and allergies purely
        so we can filter out ingredients that are commonly avoided in those
        situations. That filtering is a convenience, not a safety guarantee.
        Always read product labels and check with your doctor or pharmacist if
        you&apos;re unsure.
      </p>

      <h2 style={h2Style}>Affiliate disclosure</h2>
      <p style={pStyle}>
        Lumin recommends products from third-party brands and retailers. Some
        links are affiliate links: if you buy through them, the brand or
        retailer may pay us a commission. This never changes the price you pay.
        If a placement is paid or sponsored, we label it as such and keep it
        visually distinct from recommendations generated by your quiz or scan.
      </p>

      <h2 style={h2Style}>Eligibility and acceptable use</h2>
      <p style={pStyle}>
        You must be 18 or older to join. Don&apos;t submit other people&apos;s
        personal information, don&apos;t attempt to break, probe, overload, or
        reverse-engineer the service, and don&apos;t use automated tools to
        create entries. We may remove entries or block access if we detect
        abuse.
      </p>

      <h2 style={h2Style}>Availability</h2>
      <p style={pStyle}>
        Lumin is pre-launch software offered as-is, without warranties. We
        can&apos;t promise uninterrupted availability, and to the extent
        permitted by law we&apos;re not liable for indirect or consequential
        loss arising from use of the site. Nothing here limits rights you have
        under consumer law that can&apos;t be excluded.
      </p>

      <h2 style={h2Style}>Changes and contact</h2>
      <p style={pStyle}>
        We may update these terms as Lumin develops; material changes will be
        announced by email before taking effect. A dedicated support address is
        being set up and will be published here. In the meantime, reply to any
        email you receive from Lumin to reach us.
      </p>

      <div className="flex flex-wrap gap-4 mt-12">
        <Link href="/" className="neo-shadow neo-border px-8 py-4" style={{ background: "#f9f9f7", fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 16, letterSpacing: "0.9px", color: "#1a1c1b" }}>
          BACK HOME
        </Link>
        <Link href="/privacy" className="neo-shadow neo-border px-8 py-4" style={{ background: "#beeaf8", fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 16, letterSpacing: "0.9px", color: "#1a1c1b" }}>
          PRIVACY POLICY
        </Link>
      </div>
    </LegalChrome>
  );
}
